spring:
  application:
    name: eureka-microservice
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/