server:
  port:
    8088
spring:
  cloud:
    gateway:
      discovery:
        enabled: true
      routes:
        - id: data-microservice
          uri: lb://data-microservice
          predicates:
            - Path=/data/*
        - id: justificativo-microservice
          uri: lb://justificativo-microservice
          predicates:
            - Path=/justificativo/*
        - id: autorizacion-microservice
          uri: lb://autorizacion-microservice
          predicates:
            - Path=/autorizacion/*
        - id: sueldo-microservice
          uri: lb://sueldo-microservice
          predicates:
            - Path=/sueldo/*
        - id: reporte-microservice
          uri: lb://reporte-microservice
          predicates:
            - Path=/reporte/*
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      # defaultZone: ${EUREKA_URL:http://eureka-microservice:8761/eureka/}
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      # defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka}
  # instance:
  #   hostname: localhost